org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1-snapshot-4
minecraft_version_range=[26.1-snapshot-4,)
neo_version=26.1.0.0-alpha.8+snapshot-4
neo_version_range=[26.1.0.0-alpha,)
loader_version_range=[6.0,)

## Mod Properties
mod_id=extendedae_plus_client
mod_name=ExtendedAE Plus Client
mod_license=GNU LGPL 3.0
mod_version=1.0.9
mod_group_id=com.fish.extendedae_plus_client
mod_authors=XianYuFish001
mod_description=ExtendedAE Plus but Client only
